### ISSUE TITLE
Runtime panic when parsing apostrophe 

### ISSUE THREAD

**Issue by DouglasBrunner** [johannhof/markdown.rs#20]
## Description

I copied some text from a [random medium post](https://theestablishment.co/no-my-constitutional-right-to-abortion-did-not-cost-hillary-the-election-1fc0c84314c9) which happened to have an apostrophe in it. When I ran it through the markdown parser it compiled fine but paniced when the code was executed at runtime.

    let html : String = markdown::to_html("This doesn’t work");  // apostrophe from website
    let html : String = markdown::to_html("This does work");     // no apostrophe
    let html : String = markdown::to_html("This ' works");       // apostrophe entered via text editor

## Expected Behaviour

The library will output the string as is

## Actual Behaviour

A runtime panic

## Error Log
    thread '<unnamed>' panicked at 'byte index 11 is not a char boundary; it is inside '’' (bytes 10..13) of `This doesn’t work`', /checkout/src/libcore/str/mod.rs:1829
    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    stack backtrace:
    0: core::str::slice_error_fail
                at /checkout/src/libcore/str/mod.rs:1829
    1: core::str::traits::<impl core::ops::Index<core::ops::Range<usize>> for str>::index
                at /checkout/src/libcore/str/mod.rs:1499
    2: markdown::parser::span::parse_spans
                at /home/douglas/.cargo/registry/src/github.com-1ecc6299db9ec823/markdown-0.2.0/src/parser/span/mod.rs:37
    3: markdown::parser::block::parse_blocks
                at /home/douglas/.cargo/registry/src/github.com-1ecc6299db9ec823/markdown-0.2.0/src/parser/block/mod.rs:46
    4: markdown::parser::parse
                at /home/douglas/.cargo/registry/src/github.com-1ecc6299db9ec823/markdown-0.2.0/src/parser/mod.rs:38
    5: markdown::to_html
                at /home/douglas/.cargo/registry/src/github.com-1ecc6299db9ec823/markdown-0.2.0/src/lib.rs:25
    6: blog::post::get_one
                at ./src/post/mod.rs:37
    7: blog::post::rocket_route_fn_get_one
                at ./src/post/mod.rs:24
    8: rocket::rocket::Rocket::route
                at /home/douglas/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.2.3/src/rocket.rs:244
    9: rocket::rocket::Rocket::dispatch
                at /home/douglas/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.2.3/src/rocket.rs:192
    10: <rocket::rocket::Rocket as hyper::server::Handler>::handle
                at /home/douglas/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.2.3/src/rocket.rs:72
    11: <hyper::server::Worker<H>>::keep_alive_loop
                at /home/douglas/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.5/src/server/mod.rs:341
    12: <hyper::server::Worker<H>>::handle_connection
                at /home/douglas/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.5/src/server/mod.rs:287
    13: hyper::server::handle::{{closure}}
                at /home/douglas/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.5/src/server/mod.rs:246
    14: hyper::server::listener::spawn_with::{{closure}}
                at /home/douglas/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.5/src/server/listener.rs:50
    15: <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once
                at /checkout/src/libstd/panic.rs:296
    16: std::panicking::try::do_call
                at /checkout/src/libstd/panicking.rs:454
    17: __rust_maybe_catch_panic
                at /checkout/src/libpanic_unwind/lib.rs:98
    18: std::panicking::try
                at /checkout/src/libstd/panicking.rs:433
    19: std::panic::catch_unwind
                at /checkout/src/libstd/panic.rs:361
    20: std::thread::Builder::spawn::{{closure}}
                at /checkout/src/libstd/thread/mod.rs:360
    21: <F as alloc::boxed::FnBox<A>>::call_box
                at /checkout/src/liballoc/boxed.rs:640
    22: std::sys::imp::thread::Thread::new::thread_start
                at /checkout/src/liballoc/boxed.rs:650
                at /checkout/src/libstd/sys_common/thread.rs:21
                at /checkout/src/libstd/sys/unix/thread.rs:84
    23: start_thread
    24: clone

**Comment by johannhof** [comment]
Closed by #21
