### ISSUE TITLE
Outdated version on crates.io

### ISSUE THREAD

**Issue by bstut** [johannhof/markdown.rs#25]
"Last Updated
10 months ago"

**Comment by MightyPork** [comment]
just got bitten by that and the utf-8 panic.

quick & dirty fix:

```
[dependencies]
markdown = { git = "https://github.com/johannhof/markdown.rs" }
```

**Comment by PENGUINLIONG** [comment]
it seems it's extremely passively maintained now... If you want a stable markdown processor directly available from crates.io, actually i would recommend pulldown-cmark.

**Comment by johannhof** [comment]
While I would still recommend pulldown-cmark for the time being I'll try to get this updated on crates.io...
