### ISSUE TITLE
I'll claim "Reference-style links"

### ISSUE THREAD

**Issue by br0p0p** [johannhof/markdown.rs#27]
@johannhof is this project still active? I'm willing to contribute but I see an unmerged PR (#26) from Dec. 11.

**Comment by johannhof** [comment]
Hi there, that's a great question. I'm not actively working on this but I should really review that pull request. I'll get to it soon. If you're willing to contribute more than just ref-style link I can also invite you as a maintainer!

**Comment by spacekookie** [comment]
Any news? :sweat_smile:  Do you maybe want to just add some other people with commit bit to do some work on this crate @johannhof? It'd be good to have a well maintained markdown crate (with a simple name)

**Comment by genuinebyte** [comment]
@br0p0p still willing to contribute :sweat_smile:? I like this crate more than pulldown_cmark and I'm willing maintain it if you don't want to, @johannhof.

**Comment by johannhof** [comment]
I added @genuinebyte as a contributor, happy to give out further contributor rights on GitHub to anyone interested but will be understandably more conservative about ownership on crates.io.
