### ISSUE TITLE
Could you please submit the utf-8 fix to lib.rs?

### ISSUE THREAD

**Issue by kuangshengkai** [johannhof/markdown.rs#31]
I installed the module in cargo for version 0.2.0 and met with the utf-8 defect which had been fixed in this repository. Now I work it around by using the source code instead of installing from cargo.

**Comment by genuinebyte** [comment]
I published an updated version of this crate under the name `markly` to crates.io. You can find it [here](https://crates.io/crates/markly). It merges in #26 and #30, as well as fixes some the warnings. Further, it supports reference style links. I hope the changes can be merged here, but until then you can use markly.rs directly in place of markdown.rs by replacing
```rust
extern crate markdown;
```

with

```rust
use markly as markdown;
```

**Comment by johannhof** [comment]
@genuinebyte I have merged #32 and added you to the repository. Feel free to merge #26, though you may need to do some simple merge conflicts. I'm happy to publish on crates though I should probably add you as an author there as well, if you like.

**Comment by johannhof** [comment]
(Sorry for the delay and thanks for moving this forward)
