### ISSUE TITLE
Performance issue?

### ISSUE THREAD

**Issue by joepio** [johannhof/markdown.rs#33]
I just tried this crate in a project, but my response times for markdown pages got absolutely huge (from 14ms to 4500ms). I have no idea what happened (did it check some HTTP URLs or something?).

**Comment by johannhof** [comment]
Note that this is not actively maintained so I'd recommend switching to pulldown-cmark. With that said, I don't see what would cause such an extreme performance regression, can you share the markdown file you're trying to parse?

**Comment by joepio** [comment]
Thanks for the quick reply! I tried the comrak library, and that one worked fine. 

The MD string was:

```
Signed Integer, max 64 bit.
Max value: [`9223372036854775807`](https://en.wikipedia.org/wiki/9,223,372,036,854,775,807)

e.g. `-420`
```

Rest of the source code (now replaced with a different MD engine) found [here](https://github.com/joepio/atomic/blob/master/server/src/render_atom.rs).

**Comment by johannhof** [comment]
I added this as a test case and it runs fine on my machine (and on CI), closing for now.
